name: Build and Publish

on:
  push:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build random-logger
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/random-logger:${GITHUB_SHA} \
            ./random-logger

      - name: Push random-logger
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/random-logger:${GITHUB_SHA}

      - name: Build ping-pong
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:${GITHUB_SHA} \
            ./ping-pong

      - name: Push ping-pong
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        run: |
          kustomize edit set image random-logger=${{ secrets.DOCKERHUB_USERNAME }}/random-logger:${GITHUB_SHA}
          kustomize edit set image ping-pong=${{ secrets.DOCKERHUB_USERNAME }}/ping-pong:${GITHUB_SHA}

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "kustomization.yaml"
          message: New version released ${{ github.sha }}
