apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: logger-pingpong-svc
spec:
  type: NodePort
  selector:
    app: logger-pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
