name: Build and Publish to production

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          docker build -t asfalfa/todo-frontend:${{ github.ref_name }} frontend/
          docker build -t asfalfa/todo-backend:${{ github.ref_name }} backend/
          docker build -t asfalfa/todo-broadcaster:${{ github.ref_name }} broadcaster/

      - name: Push images
        run: |
          docker push asfalfa/todo-frontend:${{ github.ref_name }}
          docker push asfalfa/todo-backend:${{ github.ref_name }}
          docker push asfalfa/todo-broadcaster:${{ github.ref_name }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update production images
        working-directory: apps/production
        run: |
          kustomize edit set image asfalfa/todo-frontend:${{ github.ref_name }}
          kustomize edit set image asfalfa/todo-backend:${{ github.ref_name }}
          kustomize edit set image asfalfa/todo-broadcaster:${{ github.ref_name }}

      - name: Commit kustomization changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "apps/production/kustomization.yaml"
          message: "Release production ${{ github.ref_name }}"
          push: true
