apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: exercises
  name: logger-pingpong-route
spec:
  parentRefs:
    - name: logger-pingpong-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: logger-pingpong-svc
          port: 80
