apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-controller-role
rules:
  - apiGroups: ["example.com"]
    resources: ["dummysites", "dummysites/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: [""]
    resources: ["configmaps", "pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
