apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: exercises
  name: logger-pingpong-route
spec:
  parentRefs:
    - name: logger-pingpong-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: logger-pingpong-svc-v1
          port: 80
          weight: 75
        - name: logger-pingpong-svc-v2
          port: 80
          weight: 25
