apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: exercises
  name: logger-pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-pingpong
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: pingpong-cpu-analysis
                args:
                  - name: threshold
                    value: "0.5"
  template:
    metadata:
      labels:
        app: logger-pingpong
    spec:
      containers:
        - name: random-logger
          image: asfalfa/random-logger:v8
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          env:
            - name: PORT
              value: "8080"
            - name: PINGS_URL
              value: "http://localhost:8081/pings"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-config
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          ports:
            - containerPort: 8080

        - name: ping-pong
          image: asfalfa/ping-pong:v7
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 2
            periodSeconds: 5
          env:
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres.exercises.svc.cluster.local:5432/pingpong"
          ports:
            - containerPort: 8081

      volumes:
        - name: config-volume
          configMap:
            name: logger-config
            items:
              - key: information.txt
                path: information.txt
