name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${GITHUB_SHA} \
            ./backend

      - name: Push backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${GITHUB_SHA}

      - name: Build frontend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:${GITHUB_SHA} \
            ./frontend

      - name: Push frontend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:${GITHUB_SHA}

      - name: Build broadcaster
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-broadcaster:${GITHUB_SHA} \
            ./broadcaster

      - name: Push broadcaster
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-broadcaster:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        run: |
          kustomize edit set image todo-frontend=${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:${GITHUB_SHA}
          kustomize edit set image todo-backend=${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${GITHUB_SHA}
          kustomize edit set image todo-broadcaster=${{ secrets.DOCKERHUB_USERNAME }}/todo-broadcaster:${GITHUB_SHA}

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "kustomization.yaml"
          message: New version released ${{ github.sha }}
